### ISSUE TITLE
refactor this repo to the mobile app repo

### ISSUE THREAD

**Issue by kwhitehall** [Aerolyzer/Aerolyzer_App#1]
Let's make this repo strictly for the app. In addition to renaming the repo to Aerolyzer_app, some suggestions for the site are

- [x] move the "let's get started page" to the top
- [x] move the Aerolyzer page to the 2nd page, and connect the learn more button to the project website.

- [x] remove the about pages and the team pages

**Comment by colliell** [comment]
See commit https://github.com/Aerolyzer/Aerolyzer_App/commit/eb60d20260722f2618068a7237de4ae2f5f188bc

**Comment by kwhitehall** [comment]
Thanks @colliell!
