### ISSUE TITLE
Aerolyzer Web Application Internal Server Error - Verify Fix

### ISSUE THREAD

**Issue by khlam** [Aerolyzer/Aerolyzer_App#54]
Recap: Over the weekend I messed up trying to install new libraries in the AWS server that hosts http://ec2-54-152-58-132.compute-1.amazonaws.com/app/ . I believe I ran  `sudo apt update && sudo apt upgrade` which overwrote several config files. 

During our meeting it was noted that when running `sudo ./setup.sh` the following error appeared:
`ImportError: libSM.so.6: cannot open shared object file: No such file or directory`

Further research indicated this was because of a depreciated dependency. I ran the following:
`sudo apt-get install -y python-qt4`

Now the web application seems to be running I'm able to log in. @kwhitehall could you please confirm that it's all good?

**Comment by kwhitehall** [comment]
Thanks @lamki88, great debugging on your (guys) end! It works as expected on my end. May need to add that as a dependency on in the run_production script. Please open up another issue accordingly. Good work again!

**Comment by khlam** [comment]
Migrating issue to #55
